
const data={
    slideImage:[
        {
            _id:1,
            image:"/Images/FrontBanner/image1.jpg"
        },
        {
            _id:2,
            image:"/Images/FrontBanner/image2.jpg"
        },
        {
            _id:3,
            image:"/Images/FrontBanner/image3.jpg"
        },
        {
            _id:4,
            image:"/Images/FrontBanner/image4.jpg"
        },
        {
            _id:5,
            image:"/Images/FrontBanner/image5.jpg"
        },
        {
            _id:6,
            image:"/Images/FrontBanner/image6.jpg"
        },{
            _id:7,
            image:"/Images/FrontBanner/image7.jpg"
        }
     ],
    categoryImage:[
        {
            _id:1,
            title:'Men',
            image:"/Images/Category/cimage1.jpg"
        },
        {
            _id:2,
            title:'Woman',
            image:"/Images/Category/cimage2.jpg"
        },
        {
            _id:3,
            title:'kids',
            image:"/Images/Category/cimage3.jpg"
        },
    ],
    ScrollProducts:[
    {
        MensProduct:[
            {
                _id:1,
                title:'Mens',
                image:'/Images/products/boy4.jpg',
                price:'20.00'
            },
            {
                _id:2,
                title:'Mens',
                image:'/Images/products/boy5.jpg',
                price:'80.00'
            },
            {
                _id:3,
                title:'Mens',
                image:'/Images/products/boy6.jpg',
                price:'90.00'
            },
            {
                _id:4,
                title:'Mens',
                image:'/Images/products/boy7.jpg',
                price:'20.00'
            }
        ],
        GirlsProduct:[
            {
                _id:1,
                title:'Girl',
                image:'/Images/products/girl4.jpg',
                price:'20.00'
            },
            {
                _id:2,
                title:'Girl',
                image:'/Images/products/girl5.jpg',
                price:'80.00'
            },
            {
                _id:3,
                title:'Girl',
                image:'/Images/products/girl5.jpg',
                price:'90.00'
            },
            {
                _id:4,
                title:'Girl',
                image:'/Images/products/girl6.jpg',
                price:'20.00'
            }
        ],
        KidsProduct:[
            {
                _id:1,
                title:'Kids',
                image:'/Images/products/kids4.jpg',
                price:'20.00'
            },
            {
                _id:2,
                title:'Kids',
                image:'/Images/products/kids5.jpg',
                price:'80.00'
            },
            {
                _id:3,
                title:'Kids',
                image:'/Images/products/kids6.jpg',
                price:'90.00'
            },
            {
                _id:4,
                title:'Kids',
                image:'/Images/products/kids7.jpg',
                price:'20.00'
            }
        ],
    } 
],
    ViewProduct:[
        {
            _id:1,
            title:'Shirt',
            category:'Mens',
            desc:'Shirt For mens wear',
            image:"/Images/fullView/boy11.jpg",
            images1:"/Images/fullView/boy12.jpg",
            images2:"/Images/fullView/boy13.jpg",
            images3:"/Images/fullView/boy14.jpg",
            price:'90.00'
        },
        {
            _id:2,
            title:'Shirt',
            category:'Mens',
            desc:'Shirt For mens wear',
            image:"/Images/fullView/boy21.jpg",
            images1:"/Images/fullView/boy22.jpg",
            images2:"/Images/fullView/boy23.jpg",
            images3:"/Images/fullView/boy24.jpg",
            price:'95.00'
        },
        {
            _id:3,
            title:'Shirt',
            category:'Mens',
            desc:'Shirt For mens wear',
            image:"/Images/fullView/boy31.jpg",
            images1:"/Images/fullView/boy32.jpg",
            images2:"/Images/fullView/boy33.jpg",
            images3:"/Images/fullView/boy34.jpg",
            price:'110.00'
        },
        {
            _id:4,
            title:'causal',
            category:'girls',
            desc:'Girls Modern wear',
            image:'/Images/fullView/girl11.jpg',
            images1:'/Images/fullView/girl12.jpg',
            images2:'/Images/fullView/girl13.jpg',
            images3:'/Images/fullView/girl14.jpg',
            price:'100.00'
        },
        {
            _id:5,
            title:'causal',
            category:'girls',
            desc:'Girls Modern wear',
            image:'/Images/fullView/girl21.jpg',
            images1:'/Images/fullView/girl22.jpg',
            images2:'/Images/fullView/girl23.jpg',
            images3:'/Images/fullView/girl24.jpg',
            price:'120.00'
        },
        {
            _id:6,
            title:'causal',
            category:'girls',
            desc:'Girls Modern wear',
            image:'/Images/fullView/girl31.jpg',
            images1:'/Images/fullView/girl32.jpg',
            images2:'/Images/fullView/girl33.jpg',
            images3:'/Images/fullView/girl34.jpg',
            price:'40.00'
        },
        {
            _id:7,
            title:'Fancy',
            category:'kids',
            desc:'Kids Fancy Wear',
            image:'/Images/fullView/kids11.jpg',
            images1:'/Images/fullView/kids12.jpg',
            images2:'/Images/fullView/kids13.jpg',
            images3:'/Images/fullView/kids14.jpg',
            price:'80.00'
        },
        {
            _id:8,
            title:'Fancy',
            category:'kids',
            desc:'Kids Fancy Wear',
            image:'/Images/fullView/kids21.jpg',
            images1:'/Images/fullView/kids22.jpg',
            images2:'/Images/fullView/kids23.jpg',
            images3:'/Images/fullView/kids24.jpg',
            price:'50.00'
        },
        {
            _id:9,
            title:'Fancy',
            category:'kids',
            desc:'Kids Fancy Wear',
            image:'/Images/fullView/kids31.jpg',
            images1:'/Images/fullView/kids32.jpg',
            images2:'/Images/fullView/kids33.jpg',
            images3:'/Images/fullView/kids34.jpg',
            price:'110.00'
        },
        
     ]
    
}

module.exports= data



